#!/bin/bash

SCRIPT_ABS_PATH=$( cd "$(dirname "$0")" ; pwd -P )
PACKAGE_ABS_PATH=${SCRIPT_ABS_PATH%/*}

export PYTHONPATH=$PYTHONPATH:"$PACKAGE_ABS_PATH"

source $SCRIPT_ABS_PATH/env/bin/activate
python $SCRIPT_ABS_PATH/src/main.py $@
deactivate
